# Generated by Django 3.0.6 on 2021-05-07 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20210507_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='conclusion_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
