# Generated by Django 3.0.6 on 2021-05-07 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20210507_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='conclusion_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
