# Generated by Django 3.0.6 on 2021-05-07 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20210507_0102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='description',
            new_name='title',
        ),
    ]
